#:kivy 2.3.1

#:import MDGridLayout kivymd.uix.gridlayout
#:import MDFloatLayout kivymd.uix.floatlayout
#:import MDBoxLayout kivymd.uix.boxlayout
#:import MDStackLayout kivymd.uix.stacklayout
#:import Image kivy.uix.image

<TechDemoRoot>:
    cols: 2
    rows: 1

    MDFloatLayout:
        id: col_left

        Image:
            id: capture_image
            pos: 0, 200
            size: self.texture_size

    MDStackLayout:
        id: col_right
        orientation: 'tb-lr'